/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gephi.plugin.hadoop.connector;

import org.openide.util.NbPreferences;

final class EtoshaPanel extends javax.swing.JPanel {

    private final EtoshaOptionsPanelController controller;

    EtoshaPanel(EtoshaOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTf_ETOSHA_HOST = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTf_ETOSHA_DB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jLabel1.text")); // NOI18N

        jTf_ETOSHA_HOST.setText(org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jTf_ETOSHA_HOST.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jLabel2.text")); // NOI18N

        jTf_ETOSHA_DB.setText(org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jTf_ETOSHA_DB.text")); // NOI18N
        jTf_ETOSHA_DB.setToolTipText(org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jTf_ETOSHA_DB.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jLabel3.text")); // NOI18N

        jTextField3.setText(org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jTextField3.text")); // NOI18N
        jTextField3.setToolTipText(org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jTextField3.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jButton1.text")); // NOI18N
        jButton1.setToolTipText(org.openide.util.NbBundle.getMessage(EtoshaPanel.class, "EtoshaPanel.jButton1.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTf_ETOSHA_HOST, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jTf_ETOSHA_DB)
                    .addComponent(jTextField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTf_ETOSHA_HOST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTf_ETOSHA_DB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(324, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {

        this.jTf_ETOSHA_HOST.setText(NbPreferences.forModule(EtoshaPanel.class).get("ETOSHA_HOST", "www.semanpix.de"));
        this.jTf_ETOSHA_DB.setText(NbPreferences.forModule(EtoshaPanel.class).get("ETOSHA_DB", "/opendata/wiki"));
        
        HadoopClusterDefaults.ETOSHA_HOST = this.jTf_ETOSHA_HOST.getText();
        HadoopClusterDefaults.ETOSHA_DB = this.jTf_ETOSHA_DB.getText();

        HadoopClusterDefaults.notifyChangeListeners();
    }

    void store() {

        this.jTf_ETOSHA_HOST.setText(NbPreferences.forModule(EtoshaPanel.class).get("ETOSHA_HOST", "www.semanpix.de"));
        this.jTf_ETOSHA_DB.setText(NbPreferences.forModule(EtoshaPanel.class).get("ETOSHA_DB", "/opendata/wiki"));
        
        HadoopClusterDefaults.ETOSHA_HOST = this.jTf_ETOSHA_HOST.getText();
        HadoopClusterDefaults.ETOSHA_DB = this.jTf_ETOSHA_DB.getText();

        NbPreferences.forModule(EtoshaPanel.class).put("ETOSHA_HOST", this.jTf_ETOSHA_HOST.getText() );
        NbPreferences.forModule(EtoshaPanel.class).put("ETOSHA_DB", this.jTf_ETOSHA_DB.getText() );

        HadoopClusterDefaults.notifyChangeListeners();
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTf_ETOSHA_DB;
    private javax.swing.JTextField jTf_ETOSHA_HOST;
    // End of variables declaration//GEN-END:variables
}
